$('.owl-carousel').owlCarousel({
    loop:true,
    margin:50,
    nav:true,
    responsive:{
        0:{
            items:4
        },
        600:{
           items:2
        },
        1000:{
            items:3
        }
    }
})